#!/usr/bin/env ash

set -e

source colors.sh

prettyPrint "\n${light_cyan}################################################"
prettyPrint "${light_cyan}####                                         ###"
prettyPrint "${light_cyan}####               ${cyan}${underline}${bold}CF Push job${reset}${light_cyan}               ###"
prettyPrint "${light_cyan}####                                         ###"
prettyPrint "${light_cyan}################################################"

cd $HOME

prettyPrint "${yellow}Extracting manifest ..."
echo "$APP_MANIFEST" > manifest.yaml

prettyPrint "${yellow}Downloading application ..."
mkdir -p app
(cd app && wget -qcO- "$APP_URL" | tar xz)

prettyPrint "${yellow}Checking CF CLI ..."
cf version

prettyPrint "${yellow}Logging to CF ..."
if [[ -n "${SKIP_SSL_VALIDATION}" ]]; then
  FLAGS="--skip-ssl-validation"
  prettyPrint "${red}Skipping ${bold}SSL validation${reset}${red} requested!"
fi
cf api "$CF_API" "$FLAGS"
cf auth
cf target -o "$CF_ORG" -s "$CF_SPACE"

prettyPrint "${yelow}Pushing application ..."
cf push -f manifest.yaml -p app

echo "${yellow}Done."